require("mohd.plugins-setup")
require("mohd.core.options")
require("mohd.core.keymaps")
require("mohd.core.colorscheme")
require("mohd.plugins.comment")
require("mohd.plugins.nvim-tree")
require("mohd.plugins.lualine")
require("mohd.plugins.telescope")
require("mohd.plugins.nvim-cmp")
require("mohd.plugins.lsp.mason")
require("mohd.plugins.lsp.lspsaga")
require("mohd.plugins.lsp.lspconfig")
require("mohd.plugins.lsp.null-ls")
require("mohd.plugins.autopairs")
require("mohd.plugins.treesitter")
require("mohd.plugins.gitsigns")
-- require("mohd.plugins.copilot")
